apiVersion: v1
kind: Service
metadata:
  name: {{ include "smart-home-monolith.fullname" . }}
  labels:
    {{- include "smart-home-monolith.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "smart-home-monolith.selectorLabels" . | nindent 4 }}


---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service-mono
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30434
  selector:
    app: smart-home-monolith-pg
    tier: database