apiVersion: v2
name: srv-devices
keywords:
  - sprint-3
type: application
description: A Helm chart for the srv-devices service
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: "15.5.20"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
#  - name: kusk-gateway
#    version: 0.0.65    
#    repository: https://kubeshop.github.io/helm-charts