openapi: 3.0.3
info:
  title: Swagger SmartHome - OpenAPI 1.0
  description: |-
    Описание API для микросервиса «Телеметрия» системы SmartHome.
    Задача микросервиса - управлять и обрабатывать данные с устройств умного дома.
  contact:
    email: ilnur@smarthome.ru
  version: 1.0.0
servers:
  - url: https://smarthome.ru/api/v1
tags:
  - name: telemetry
    description: Устройства умного дома
paths:
  /devices/{device_id}/telemetry/latest:
    get:
      tags:
        - telemetry
      summary: Получить данные датчика
      description: Получение последних данных телеметрии
      operationId: getLatestTelemetry
      parameters:
        - name: device_id
          in: path
          description: ID of device
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Успешная операция
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/telemetry'          
        '400':
          description: Не верный номер устройства
        '404':
          description: Устройство не найдено
        '500':
          description: Ошибка на сервере
        '502':
          description: Ошибочный шлюз
          
  /devices/{device_id}/{date_from}/{date_to}/telemetry:
    get:
      tags:
        - telemetry
      summary: Получение данных датчика
      description: Получение исторических данных телеметрии
      operationId: editDeviceStatus
      parameters:
        - name: device_id
          in: path
          description: ID of device
          required: true
          schema:
            type: integer
            format: int64
        - name: date_from
          in: path
          description: Дата начала периода
          required: true
          schema:
            type: string
            example: "2024-01-01"
        - name: date_to
          in: path
          description: Дата конца периода
          required: true
          schema:
            type: string
            example: "2024-03-31"
      responses:
        '200':
          description: Успешная операция
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/telemetry'          
        '400':
          description: Не верный формат даты или номер устройства
        '404':
          description: Устройство не найдено
        '500':
          description: Ошибка на сервере
        '502':
          description: Ошибочный шлюз
components:
  schemas:
    telemetry:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        device_id:
          type: integer
          format: int32
          example: 2
        Home_id:
          type: integer
          format: int32
          example: 123
        Room_id:
          type: integer
          format: int32
          example: 1
        created_date_time:
          type: string
          example: '2024-12-01 12:00:00'
        value:
          type: string
          example: '20 градусов'
      xml:
        name: telemetry


