replicaCount: 1

image:
  repository: ghcr.io/synaxintelligence/srv-docs
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 80

imagePullSecrets:
  - name: ghcr-secret

ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80