apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      initContainers:
        - name: wait-for-zookeeper
          image: busybox
          command: [ 'sh', '-c', 'until nc -z zookeeper {{ .Values.zookeeper.port }}; do echo waiting for zookeeper; sleep 2; done;' ]
      containers:
        - name: kafka
          image: {{ .Values.kafka.image }}
          ports:
            - containerPort: {{ .Values.kafka.port }}
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: {{ .Values.kafka.advertisedListeners }}
            - name: KAFKA_LISTENERS
              value: {{ .Values.kafka.listeners }}
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: {{ .Values.kafka.listenerSecurityProtocolMap }}
            - name: KAFKA_LISTENER_NAME
              value: {{ .Values.kafka.listenerName }}
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: {{ .Values.kafka.interBrokerListenerName }}
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: {{ .Values.kafka.zookeeperConnect }}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
    - port: {{ .Values.kafka.port }}
  selector:
    app: kafka
