name: ci

on:
  push:
    branches:
      - sprint_3
  pull_request:
    branches:
      - sprint_3

env:
  DOCKER_IMAGE_NAME: ghcr.io/synaxintelligence/srv-mono
  DOCKER_IMAGE_TAG: latest
  CHART_NAME: srv-mono
  CHART_VERSION: 1.0.0

jobs:
  # Stage 1: Docker
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: smart-home-monolith
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Stage 2: Helm
  helm-deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.1

      - name: Lint Helm Chart
        run: helm lint charts/${{ env.CHART_NAME }}

      - name: Package Helm chart
        run: |
          helm package charts/${{ env.CHART_NAME }} --version ${{ env.CHART_VERSION }}

      - name: Login to Yandex Container Registry
        uses: docker/login-action@v2
        with:
          registry: cr.yandex
          username: oauth
          password: ${{ secrets.YC_OAUTH }}

      - name: Push Helm chart to Yandex Container Registry
        run: |
          helm push ${{ env.CHART_NAME }}-${{ env.CHART_VERSION }}.tgz oci://cr.yandex/${{ secrets.YC_REGISTRY_ID }}/charts
